spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user_service
          uri: lb://USER-SERVICE/user-service/**
          predicates:
            - Path=/user-service/**
        - id: main_service
          uri: lb://USER-SERVICE/main/**
          predicates:
            - Path=/main/**
        - id: first_service
          uri: lb://FIRST-SERVICE/first/**
          predicates:
            - Path=/first/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka