FROM bellsoft/liberica-openjdk-alpine:17
# or
# FROM openjdk:8-jdk-alpine
# FROM openjdk:11-jdk-alpine

# CMD ["./gradlew", "clean", "build"]
# or Maven 
CMD ["./mvnw clean && ./mvnw", "package","-DskipTests"]

VOLUME /tmp

# ARG JAR_FILE=build/libs/*.jar
# or Maven
# ARG JAR_FILE_PATH=target/*.jar

COPY app.jar app.jar

EXPOSE 10000

ENTRYPOINT ["java","-jar","-Dserver.port=10000","/app.jar"]