spring:
  application:
    name: user-service
  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pmh?characterEncoding=UTF-8&serverTimezone=UTC
  sql:
    init:
      platform: mysql

mh:
  value: changeValue

mybatis:
  # resources/mapper/ ? ?? ?? xml ??
  mapper-locations: mapper/*.xml

server:
  port: 8089

eureka:
  #  instance:
  #    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

token:
  expiration_time: 86400000
  secret: mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004mh1004

gateway:
  ip: 127.0.0.1
